"""init

Revision ID: 9c9805eb8b30
Revises: 
Create Date: 2021-12-14 20:41:18.713915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c9805eb8b30"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("signature", sa.JSON(), nullable=False),
        sa.Column("training_data", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name", "version"),
    )
    op.create_table(
        "reports",
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("model_version", sa.Integer(), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("model_name", "model_version"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    op.drop_table("models")
    # ### end Alembic commands ###
