version: "0.1"
services:
  shell-ui:
    image: hydrosphere/shell-ui:latest
    ports:
      - "4200:8080"

  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=monitoring"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: "server /data --console-address \":9001\""

  monitoring-manager:
    image: hydrosphere/monitoring-manager:latest
    depends_on:
      - db
      - minio
    environment:
      - "AWS_REGION=us-west-1"
    ports:
      - "8080:8080"
      - "8081:8081"

  # stat-plugin:
  #   image: hydrosphere/drift-report-plugin:latest
  #   depends_on:
  #     - monitoring-manager
  #     #ports:
  #     #- "5001:5001"
  #   environment:
  #     # - "GRPC_VERBOSITY=DEBUG"
  #     # - "GRPC_TRACE=all,-timer_check"
  #     - "ENDPOINT_OVERRIDE=http://minio:9000"
  #     - "HTTP_PORT=5000"
  #     - "MANAGER_ADDR=monitoring-manager:8081"
  #     - "AWS_ACCESS_KEY_ID=minioadmin"
  #     - "AWS_SECRET_ACCESS_KEY=minioadmin"
  #     - "SELF_ADDR=http://stat-plugin:5000"
  be:
    image: hydrosphere/profiler:latest
    depends_on:
      - monitoring-manager
    environment:
      - "AWS_ACCESS_KEY_ID=minioadmin"
      - "AWS_SECRET_ACCESS_KEY=minioadmin"
