name: ci

on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run Python Tests
        uses: ./.github/actions/tests
        with:
          python-version: 3.8
