name: ci

on:
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-20.04
    name: "Setup Python & Run Tests"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Install dependencies
        shell: bash
        run: "poetry install"

      - name: Test code
        shell: bash
        run: "poetry run pytest tests"

  Build_image:
    runs-on: ubuntu-20.04
    name: "Build Image"
    env:
      IMAGE: drift-report-plugin # name of the built image
      REGISTRY: hydrosphere
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            GIT_HEAD_COMMIT=${{ github.sha }}
            GIT_CURRENT_BRANCH=${{ github.ref }}
      
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
